fixtures:
  repositories:
    classroom_legacy: "git://github.com/puppetlabs/pltraining-classroom_legacy.git"
  forge_modules:
    abalone: "binford2k/abalone"
    dirtree: "pltraining/dirtree"
    dockeragent: "pltraining/dockeragent"
    epel: "stahnma/epel"
    firewall: "puppetlabs/firewall"
    chocolatey: "chocolatey/chocolatey"
    docker: "garethr/docker"
    git: "puppetlabs/git"
    inifile: "puppetlabs/inifile"
    pe_puppetserver_gem: "puppetlabs/pe_puppetserver_gem"
    puppet_enterprise: "geoffwilliams/puppet_enterprise"
    puppetserver_gem: "puppetlabs/puppetserver_gem"
    puppetfactory: "pltraining/puppetfactory"
    stdlib: "puppetlabs/stdlib"
    vcsrepo: "puppetlabs/vcsrepo"
    rbac: "pltraining/rbac"
    ssh: "attachmentgenie/ssh"
    stunnel: "arusso/stunnel"
    staging: "puppet/staging"
    sysctl: "fiddyspence/sysctl"
    showoff: "pltraining/showoff"
    userprefs: "pltraining/userprefs"
  symlinks:
    classroom: "#{source_dir}"
