fixtures:
  forge_modules:
    chocolatey: "puppetlabs/chocolatey"
    classroom_legacy: "pltraining/classroom_legacy"
    abalone: "binford2k/abalone"
    dirtree: "pltraining/dirtree"
    dockeragent: "pltraining/dockeragent"
    epel: "stahnma/epel"
    firewall: "puppetlabs/firewall"
    docker: "garethr/docker"
    git: "puppetlabs/git"
    inifile: "puppetlabs/inifile"
    pe_puppetserver_gem: "puppetlabs/pe_puppetserver_gem"
    powershell: "puppetlabs/powershell"
    puppet_enterprise: "geoffwilliams/puppet_enterprise"
    puppetserver_gem: "puppetlabs/puppetserver_gem"
    puppetfactory: "pltraining/puppetfactory"
    registry: "puppetlabs/registry"
    stdlib: "puppetlabs/stdlib"
    vcsrepo: "puppetlabs/vcsrepo"
    rbac: "pltraining/rbac"
    ssh: "attachmentgenie/ssh"
    stunnel: "arusso/stunnel"
    staging: "puppet/staging"
    sysctl: "fiddyspence/sysctl"
    showoff: "pltraining/showoff"
    userprefs: "pltraining/userprefs"
    windows_env: "badgerious/windows_env"
  symlinks:
    classroom: "#{source_dir}"
